name: Release What

on:
  push:
    branches: ["main"]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: npm i -g --force corepack && corepack enable

      - name: Install Node.js, NPM and PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install

      # Linux-specific setup
      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools rpm libfuse2 squashfs-tools

      - name: Release Electron app
        uses: daltonmenezes/action-electron-builder@v1.0.1
        with:
          package_manager: "pnpm"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
