name: Release What

on:
  push:
    branches: ["main"]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libarchive-tools rpm libfuse2 squashfs-tools

      - name: Patch electron-builder to avoid pnpm list bug (Windows only)
        if: matrix.os == 'windows-latest'
        run: |
          sed -i 's/pnpm list --prod --json --depth Infinity/pnpm list --prod --json --depth 2/' node_modules/app-builder-lib/out/util/yarn.js || true

      - name: Release Electron app
        uses: daltonmenezes/action-electron-builder@v1.0.1
        with:
          package_manager: "pnpm"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: true
          skip_build: true
